Logga.Core/Controllers/LoggaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using Dapper;
using Logga.Data;

namespace Logga.Controllers
{
    public class LoggaController : Controller
    {
         public ActionResult CreateError()
        {
            throw new Exception("Hi, I'm Logga and i'm your friend!");
        }

        public ActionResult Index()
        {
            using (var connection = ConnectionConfiguration.GetOpenConnection(LoggaConfiguration._connectionString))
            {
                var loggaList = connection.Query<LoggaEntry>("SELECT * FROM LoggaEntry");

                return View(loggaList);
            }
        }

        public ActionResult Details(int id)
        {
            using (var connection = ConnectionConfiguration.GetOpenConnection(LoggaConfiguration._connectionString))
            {
                var logga = connection.Query<LoggaEntry>("SELECT * FROM LoggaEntry WHERE LoggaEntryId = @id", new { id = id}).FirstOrDefault();

                return View(logga);
            }

        }
    }
}

Logga.Core/Views/Logga/Details.cshtml
@model Logga.Data.LoggaEntry

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Hi, I'm Logga and i'm your friend!</title>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body bgcolor="white" class="container">
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Back to Index", "Index", "Logga", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <br /><br />
    <span>
        <h1>Server Error in '/' Application.<hr width="100%" size="1" color="silver"></h1>

        @*<h2> <i>@Model.Message</i> </h2>*@
    </span>

    <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

        <b> Description: </b>
        @Model.Message
        <br /><br />

        <b> Exception Details: </b>@Model.Type: @Model.Message<br>

        @*<b>Source Error:</b> <br><br>

                    <table width="100%" bgcolor="#ffffcc">
                        <tbody>
                            <tr>
                                <td>
                                    <code>
                                        <pre>
            Line 15:          public ActionResult CreateError()
            Line 16:         {
            <font color="red">Line 17:             throw new Exception("Hi, I'm Logga and i'm your friend!");
            </font>Line 18:         }
            Line 19: </pre>
                                    </code>

                                </td>
                            </tr>
                        </tbody>
                    </table>*@

        <br>

        <b> Source File: </b> @Model.Target
        <br><br>

        <b>Stack Trace:</b>

        <table width="100%" bgcolor="#ffffcc">
            <tbody>
                <tr>
                    <td>
                        <pre>
                             @Model.StackTrace
                            </pre>
                    </td>
                </tr>
            </tbody>
        </table>

        <br>
        <b>Date:</b>&nbsp;@Model.DateError
        <br /><br>

        <b>User:</b>&nbsp;@Model.User
        <br /><br>

        <b>Host:</b>&nbsp;@Model.Host
        <br /><br>
    </font>
</body>
</html>

Logga.Core/Views/Logga/Index.cshtml
@model IEnumerable<Logga.Data.LoggaEntry>

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hi, I'm Logga and i'm your Friend</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/r/bs-3.3.5/jq-2.1.4,dt-1.10.8/datatables.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/r/bs-3.3.5/jqc-1.11.3,dt-1.10.8/datatables.min.js"></script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Logga", "Index", "Logga", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container">
        <br /><br /><br /><br />
        <div class="row">
            @Html.ActionLink("Create Test Error", "CreateError")
        </div>
        <br />
        <div class="row">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.DateError)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Source)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Target)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Type)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.User)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Host)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.DateError
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Source)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Target)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Type)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.User)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Host)
                            </td>
                            <td>
                                @Html.ActionLink("Details", "Details", new { id = item.LoggaEntryId }, new { @class = "btn default btn-xs" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <script>
            jQuery(document).ready(function () {
                $('table').DataTable();
            });
        </script>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>

Logga.Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Logga", "Index", "Logga",  new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("All Erros", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br/>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Logga</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>